version: '3'

services:
  frontend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
